
### 
POST http://localhost:3000/api/geotags/
Content-Type: application/json

{
  "name": "Zuhause",
  "latitude": 48.689828750000004,
  "longitude":8.138015273157894,
  "hashtag": "#home"
}

###
GET http://localhost:3000/api/geotags/11

### 
PUT http://localhost:3000/api/geotags/11
Content-Type: application/json

{
  "name": "Neues Zuhause",
  "latitude": 49.00905655,
  "longitude":8.427388434952388,
  "hashtag": "#home2"
}

###
DELETE http://localhost:3000/api/geotags/11

###
GET http://localhost:3000/api/geotags/11